# Generated by Django 2.0.4 on 2018-05-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanjang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nanjang',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
