# Generated by Django 2.0.4 on 2018-05-03 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanjang', '0002_auto_20180501_1743'),
        ('nanjang', '0002_nanjang_like_count'),
    ]

    operations = [
    ]
