# Generated by Django 2.0.4 on 2018-04-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jujum',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jujum',
            name='menu',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='nanjang',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nanjang',
            name='menu',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
