# Generated by Django 2.0.4 on 2018-05-01 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180430_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jujum',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='nanjang',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Jujum',
        ),
        migrations.DeleteModel(
            name='Nanjang',
        ),
    ]
