# Generated by Django 2.0.4 on 2018-05-01 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jujum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField()),
                ('jujum', models.ForeignKey(on_delete=True, to='jujum.Jujum')),
            ],
        ),
    ]
