# Generated by Django 2.0.4 on 2018-05-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jujum', '0002_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='jujum',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
