# Generated by Django 2.0.4 on 2018-05-02 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jujum', '0003_jujum_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='jujum',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
