# Generated by Django 2.0.5 on 2018-05-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jujum', '0006_auto_20180506_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='jujum',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='home/%Y/%m/%d'),
        ),
    ]
