# Generated by Django 2.0.5 on 2018-05-07 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jujum', '0008_jujum_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jujum',
            options={'ordering': ['priority']},
        ),
    ]
